[pytest]
;addopts = -vs --tb=short --alluredir=./allure_results --clean-alluredir
addopts = -s --html=./reports/test_report.html --self-contained-html
testpaths = testcases
python_files = test_*.py
python_functions = test_*
python_classes = Test*
log_cli = True
log_cli_level = INFO
log_file = logs/test.log

markers =
    # 业务模块标签
    geocode: 地理编码接口
    direction: 路线规划接口
    # 优先级标签
    p0: P0阻断核心用例
    p1: P1重要业务用例
    p2: P2次要辅助用例
    p3: P3边缘兼容用例
    # 执行分组
    smoke: 冒烟测试
    regression: 迭代回归