[pytest]
;addopts = -vs --tb=short --alluredir=./allure_results --clean-alluredir
addopts = -s --html=./reports/test_report.html --self-contained-html
testpaths = testcases
python_files = test_*.py
python_functions = test_*
python_classes = Test*
log_cli = True
log_cli_level = INFO
log_file = logs/test.log